name: flutter_full_router
description: 'A powerful, dependency-free navigation engine for Flutter using the native Router API. Complete control over routing, URL parameters, guards, runtime routes, and actions.'
version: 0.0.2
homepage: https://faustobdls.dev
repository: https://github.com/faustobdls/flutter_full_router.git

environment:
  sdk: ^3.10.7
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.15.0

flutter:
